name: Test GitHub Workflow Dispatch Secrets
on:
  workflow_dispatch:
    inputs:
      super_secret:
        description: Super Secret
        required: true
jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((inputs.super_secret))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
