name: Test GitHub Workflow Dispatch Secrets
on:
  workflow_dispatch:
    inputs:
      super_secret:
        description: Super Secret
        required: true
jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Hide the inputs values to keep them private in the logs when running this workflow
        uses: levibostian/action-hide-sensitive-inputs@v1
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret input is ${{ inputs.super_secret }}"
          if [[ "${{ inputs.super_secret }}" == "76c726b7-8783-4327-bd8c-1abaf3306146" ]]; then
            echo "they are equal: ✅"
          else
            echo "they are equal: ❌"
          fi
