name: Test GitHub Workflow Dispatch Secrets
on:
  workflow_dispatch:
    inputs:
      super_secret:
        description: Super Secret
        required: true
jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "::add-mask::${{ github.event.inputs.super_secret }}"
          echo "the secret is ${{ github.event.inputs.super_secret }}"
